ChloeBaba/whistle_island

app/models/island.rb, app/models/user.rb
Hey @pankratz117 @LReed2144, could you please review the following:
- line 3 => if an island is deleted, all attached bookings should be deleted too
- line 5 =>  validate all the Island table attributes except `:photo` as it is not part of the seed file for now. Will have to be added later on
=> Add association and validation to Island model

db/seeds.rb
1.) First: create 10 fake users with User.create(...): user_1, user_2, ... user_10.
Note: create will automatically save! 
2.) Second: make 5 new fake islands with Island.new(...): island_1, island_2 .... island_5
3.) Then: Assign the five created islands to the first five users:
island_1.user = user_1
island_2.user = user_2
...
island_5.user = user_5
4.) Save the islands with island_1.save, island_2.save .... island_5.save
5.) Make 5 new bookings with Booking.new
6.)  assign the last five users to the bookings
7.) assign the 5 islands to the bookings
8.)  save the bookings
=> populate database with fake data: 10users, 5 islands, 5 bookings.

app/assets/stylesheets/config/_fonts.scss
Modified font to Alata (headers) / Open Sans (body)
=> change font

app/assets/stylesheets/config/_colors.scss
Set the colors for the titles and subtitles - might be subject to change if ugly.
=> added color scheme

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/policies/application_policy.rb
this will install the gem and edit the application controller. from now on, when implementing an controller you have to start with
1.) rails g pundit:policy modelname
2.) in modelPolicy class you config the authorization
3.) in the controller you use authorize @model
4.) update the views
it is well explained on kit "Authorization & pundit"
=> Adding pundit gem to projet

app/controllers/application_controller.rb
Addind-authentication-to-application-controller
=> Addind-authentication-to-application-controller

db/migrate/20191119104452_add_priceto_islands.rb, db/migrate/20191119105258_add_price_to_islands.rb, db/schema.rb
this will add the price per day column to our islands table
=> Add price per day to island

app/controllers/application_controller.rb, db/schema.rb
@pankratz117 @MorganeGedio @LReed2144 @tms28 
Hey there, I removed the Authentication line in the application controller as it's preventing us from testing routes.
cheers
=> Removing authentication to application controller for testing routes purposes

app/controllers/islands_controller.rb, app/models/island.rb, app/policies/island_policy.rb, app/views/islands/index.html.erb, db/schema.rb, test/policies/island_policy_test.rb
When applied you have the policy controller for islands. so now we can config the authorization
=> Add-the-islands-policy-controller

app/controllers/islands_controller.rb, app/policies/island_policy.rb, app/views/islands/index.html.erb
when applied a visitor can see all the islands on /islands
=> Visitor can see all islands

app/controllers/islands_controller.rb, app/views/islands/show.html.erb, db/schema.rb
I added : 
- the show action in controller
- the show page (show.html.erb)
=> See island page

app/controllers/islands_controller.rb, app/views/islands/edit.html.erb, db/schema.rb
Edit and update methods are up and running
=> Update island page

app/views/islands/index.html.erb
I modified the index.html.erb file so now, when you click on a islands name, you will be directed to the show page of that island.
=> island names on index page are links now. directing the show page

config/routes.rb
added nested routes for the booking. so we have them nested (after islands/island_id)
=> add routes for booking

app/policies/booking_policy.rb, test/policies/booking_policy_test.rb
Added the method set to true in the booking policy.rb
=> Added the method set to true in the booking policy.rb

app/controllers/bookings_controller.rb, app/policies/application_policy.rb, app/policies/booking_policy.rb, app/views/bookings/new.html.erb
added the new action for booking controller AND fixed a syntax error on booking_policy.rb (there was one 'end' missing)
=> Adding booking new/create feature

app/controllers/bookings_controller.rb
added the params to the bookings controller
=> add params to bookings controller

app/controllers/bookings_controller.rb, app/policies/booking_policy.rb
add create action to bookings controller. hurry up, chloe!
=> implemented create action to bookings controller

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, config/routes.rb
when applied, it will add the destroy action to the bookings controller.
within the index view the user can now see all the bookings from aur DB. so we now have to use authorization to make the user only see his islands/bookings.
=> Add destroy action to bookings controller

app/views/islands/index.html.erb
- seed.rb => islands name, description, price, availability
- index => fixed
=> Fixing index html island view

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_usersettings.scss, app/controllers/users_controller.rb, app/models/user.rb, app/policies/user_policy.rb, app/views/users/edit.html.erb, app/views/users/show.html.erb, config/routes.rb, test/policies/user_policy_test.rb
Morning! User can now edit own profile (name, email, photo).
=> Add edit action to users controller

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_island-card.scss, app/assets/stylesheets/components/_island-info.scss, app/assets/stylesheets/components/_island-photo.scss, app/views/islands/show.html.erb, db/schema.rb
grid in case we further add airbnb like feature for 2-3 pics
=> Fixed the Island cards and created a grid

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search.scss, app/controllers/islands_controller.rb, app/policies/island_policy.rb, app/views/islands/index.html.erb, app/views/pages/home.html.erb
please check the search for island page =)
=> search bar in index

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search-home.scss, app/controllers/islands_controller.rb, app/views/pages/home.html.erb
=> search bar on homepage

app/assets/stylesheets/components/_booking-dates.scss, app/assets/stylesheets/components/_card-dashboard.scss, app/assets/stylesheets/components/_dashboard-card-product.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_main-content.scss, app/assets/stylesheets/components/_row.scss, app/views/dashboards/show.html.erb
=> Dashboard show html erb page

app/views/shared/_navbar.html.erb
=> got rid of mail address in navbar

app/controllers/pages_controller.rb
I've modified the pages controller in order to skip pundit on the homepage
=> Skip pundit for the homepage
